#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef CONFIGWISESDK_SWIFT_H
#define CONFIGWISESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ARKit;
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import Parse;
@import SceneKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ConfigWiseSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



SWIFT_CLASS("_TtC13ConfigWiseSDK14EmbeddedEntity")
@interface EmbeddedEntity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK28AnchorObjectConnectionEntity")
@interface AnchorObjectConnectionEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC13ConfigWiseSDK18CatalogAwareEntity")
@interface CatalogAwareEntity : PFObject
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18AnchorObjectEntity")
@interface AnchorObjectEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC13ConfigWiseSDK9ModelNode")
@interface ModelNode : SCNNode
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK21AnchorObjectModelNode")
@interface AnchorObjectModelNode : ModelNode
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17AppListItemEntity")
@interface AppListItemEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK9ArAdapter")
@interface ArAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSCNViewDelegate>
@end



@protocol SCNSceneRenderer;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <SCNSceneRendererDelegate>
- (void)renderer:(id <SCNSceneRenderer> _Nonnull)renderer updateAtTime:(NSTimeInterval)time;
@end

@class ARSession;
@class ARFrame;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSessionDelegate>
- (void)session:(ARSession * _Nonnull)session didUpdateFrame:(ARFrame * _Nonnull)frame;
@end

@class ARCamera;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSessionObserver>
- (void)session:(ARSession * _Nonnull)session didFailWithError:(NSError * _Nonnull)error;
- (void)session:(ARSession * _Nonnull)session cameraDidChangeTrackingState:(ARCamera * _Nonnull)camera;
@end



@class UIPanGestureRecognizer;
@class UIPinchGestureRecognizer;
@class UIRotationGestureRecognizer;
@class UITapGestureRecognizer;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)handlePanGestureWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)handlePinchGestureWithRecognizer:(UIPinchGestureRecognizer * _Nonnull)recognizer;
- (void)handleRotationGestureWithRecognizer:(UIRotationGestureRecognizer * _Nonnull)recognizer;
- (void)handleSingleTapGestureWithRecognizer:(UITapGestureRecognizer * _Nonnull)recognizer;
- (void)handleDoubleTapGestureWithRecognizer:(UITapGestureRecognizer * _Nonnull)recognizer;
@end



@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AssignedMaterialEntity")
@interface AssignedMaterialEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class ConceptItemEntity;

@interface AssignedMaterialEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nullable material_id;
@property (nonatomic, copy) NSString * _Nonnull tag;
@property (nonatomic, strong) ConceptItemEntity * _Nullable conceptItem;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK13CatalogEntity")
@interface CatalogEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17CombinationEntity")
@interface CombinationEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK21CombinationItemEntity")
@interface CombinationItemEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK13CompanyEntity")
@interface CompanyEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK15ComponentEntity")
@interface ComponentEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18ComponentModelNode")
@interface ComponentModelNode : ModelNode
@end






SWIFT_CLASS_NAMED("ConceptEntity")
@interface ConceptEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface ConceptEntity (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)addConceptItemsObject:(ConceptItemEntity * _Nonnull)value;
- (void)removeConceptItemsObject:(ConceptItemEntity * _Nonnull)value;
- (void)addConceptItems:(NSSet * _Nonnull)values;
- (void)removeConceptItems:(NSSet * _Nonnull)values;
@end


@class NSNumber;
@class NSData;
@class NSDate;

@interface ConceptEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nullable conflictsMessage;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) int16_t popularity;
@property (nonatomic, strong) NSData * _Nullable thumbnail;
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic) BOOL groundEnabled;
@property (nonatomic, copy) NSString * _Nullable groundColorRgba;
@property (nonatomic, strong) NSSet * _Nullable conceptItems;
@property (nonatomic, copy) NSDate * _Nonnull lastOpened;
@end


SWIFT_CLASS_NAMED("ConceptItemEntity")
@interface ConceptItemEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ConceptItemEntity (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)addAssignedMaterialsObject:(AssignedMaterialEntity * _Nonnull)value;
- (void)removeAssignedMaterialsObject:(AssignedMaterialEntity * _Nonnull)value;
- (void)addAssignedMaterials:(NSSet * _Nonnull)values;
- (void)removeAssignedMaterials:(NSSet * _Nonnull)values;
@end



@interface ConceptItemEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull component_id;
@property (nonatomic) float positionX;
@property (nonatomic) float positionY;
@property (nonatomic) float positionZ;
@property (nonatomic) float rotationW;
@property (nonatomic) float rotationX;
@property (nonatomic) float rotationY;
@property (nonatomic) float rotationZ;
@property (nonatomic, strong) NSSet * _Nullable assignedMaterials;
@property (nonatomic, strong, getter=concept, setter=setConcept:) ConceptEntity * _Nullable concept_;
@end




SWIFT_CLASS("_TtC13ConfigWiseSDK14FileSizeEntity")
@interface FileSizeEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// An <code>SCNNode</code> which is used to provide uses with visual cues about the status of ARKit world tracking.
SWIFT_CLASS("_TtC13ConfigWiseSDK7HudNode")
@interface HudNode : SCNNode
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK12ImagesEntity")
@interface ImagesEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK20ImagesFrame360Entity")
@interface ImagesFrame360Entity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17ImagesFrameEntity")
@interface ImagesFrameEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK14MaterialEntity")
@interface MaterialEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK24ModelMeasuringUnitEntity")
@interface ModelMeasuringUnitEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK15NodeToTagEntity")
@interface NodeToTagEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface PFObject (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class PFACL;

SWIFT_CLASS("_TtC13ConfigWiseSDK10RoleEntity")
@interface RoleEntity : PFRole
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name acl:(PFACL * _Nullable)acl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC13ConfigWiseSDK11SceneEntity")
@interface SceneEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK27ScnMaterialPropertiesEntity")
@interface ScnMaterialPropertiesEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK25ScnMaterialPropertyEntity")
@interface ScnMaterialPropertyEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18SnappingAreaEntity")
@interface SnappingAreaEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK12SnappingNode")
@interface SnappingNode : SCNNode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK20TagToMaterialsEntity")
@interface TagToMaterialsEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13ConfigWiseSDK10UserEntity")
@interface UserEntity : PFUser
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef CONFIGWISESDK_SWIFT_H
#define CONFIGWISESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ARKit;
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import Parse;
@import SceneKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ConfigWiseSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



SWIFT_CLASS("_TtC13ConfigWiseSDK14EmbeddedEntity")
@interface EmbeddedEntity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK28AnchorObjectConnectionEntity")
@interface AnchorObjectConnectionEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC13ConfigWiseSDK18CatalogAwareEntity")
@interface CatalogAwareEntity : PFObject
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18AnchorObjectEntity")
@interface AnchorObjectEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC13ConfigWiseSDK9ModelNode")
@interface ModelNode : SCNNode
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK21AnchorObjectModelNode")
@interface AnchorObjectModelNode : ModelNode
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17AppListItemEntity")
@interface AppListItemEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK9ArAdapter")
@interface ArAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSCNViewDelegate>
@end



@protocol SCNSceneRenderer;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <SCNSceneRendererDelegate>
- (void)renderer:(id <SCNSceneRenderer> _Nonnull)renderer updateAtTime:(NSTimeInterval)time;
@end

@class ARSession;
@class ARFrame;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSessionDelegate>
- (void)session:(ARSession * _Nonnull)session didUpdateFrame:(ARFrame * _Nonnull)frame;
@end

@class ARCamera;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK)) <ARSessionObserver>
- (void)session:(ARSession * _Nonnull)session didFailWithError:(NSError * _Nonnull)error;
- (void)session:(ARSession * _Nonnull)session cameraDidChangeTrackingState:(ARCamera * _Nonnull)camera;
@end



@class UIPanGestureRecognizer;
@class UIPinchGestureRecognizer;
@class UIRotationGestureRecognizer;
@class UITapGestureRecognizer;

@interface ArAdapter (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)handlePanGestureWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)handlePinchGestureWithRecognizer:(UIPinchGestureRecognizer * _Nonnull)recognizer;
- (void)handleRotationGestureWithRecognizer:(UIRotationGestureRecognizer * _Nonnull)recognizer;
- (void)handleSingleTapGestureWithRecognizer:(UITapGestureRecognizer * _Nonnull)recognizer;
- (void)handleDoubleTapGestureWithRecognizer:(UITapGestureRecognizer * _Nonnull)recognizer;
@end



@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AssignedMaterialEntity")
@interface AssignedMaterialEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class ConceptItemEntity;

@interface AssignedMaterialEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nullable material_id;
@property (nonatomic, copy) NSString * _Nonnull tag;
@property (nonatomic, strong) ConceptItemEntity * _Nullable conceptItem;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK13CatalogEntity")
@interface CatalogEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17CombinationEntity")
@interface CombinationEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK21CombinationItemEntity")
@interface CombinationItemEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK13CompanyEntity")
@interface CompanyEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK15ComponentEntity")
@interface ComponentEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18ComponentModelNode")
@interface ComponentModelNode : ModelNode
@end






SWIFT_CLASS_NAMED("ConceptEntity")
@interface ConceptEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface ConceptEntity (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)addConceptItemsObject:(ConceptItemEntity * _Nonnull)value;
- (void)removeConceptItemsObject:(ConceptItemEntity * _Nonnull)value;
- (void)addConceptItems:(NSSet * _Nonnull)values;
- (void)removeConceptItems:(NSSet * _Nonnull)values;
@end


@class NSNumber;
@class NSData;
@class NSDate;

@interface ConceptEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nullable conflictsMessage;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) int16_t popularity;
@property (nonatomic, strong) NSData * _Nullable thumbnail;
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic) BOOL groundEnabled;
@property (nonatomic, copy) NSString * _Nullable groundColorRgba;
@property (nonatomic, strong) NSSet * _Nullable conceptItems;
@property (nonatomic, copy) NSDate * _Nonnull lastOpened;
@end


SWIFT_CLASS_NAMED("ConceptItemEntity")
@interface ConceptItemEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ConceptItemEntity (SWIFT_EXTENSION(ConfigWiseSDK))
- (void)addAssignedMaterialsObject:(AssignedMaterialEntity * _Nonnull)value;
- (void)removeAssignedMaterialsObject:(AssignedMaterialEntity * _Nonnull)value;
- (void)addAssignedMaterials:(NSSet * _Nonnull)values;
- (void)removeAssignedMaterials:(NSSet * _Nonnull)values;
@end



@interface ConceptItemEntity (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull component_id;
@property (nonatomic) float positionX;
@property (nonatomic) float positionY;
@property (nonatomic) float positionZ;
@property (nonatomic) float rotationW;
@property (nonatomic) float rotationX;
@property (nonatomic) float rotationY;
@property (nonatomic) float rotationZ;
@property (nonatomic, strong) NSSet * _Nullable assignedMaterials;
@property (nonatomic, strong, getter=concept, setter=setConcept:) ConceptEntity * _Nullable concept_;
@end




SWIFT_CLASS("_TtC13ConfigWiseSDK14FileSizeEntity")
@interface FileSizeEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// An <code>SCNNode</code> which is used to provide uses with visual cues about the status of ARKit world tracking.
SWIFT_CLASS("_TtC13ConfigWiseSDK7HudNode")
@interface HudNode : SCNNode
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK12ImagesEntity")
@interface ImagesEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK20ImagesFrame360Entity")
@interface ImagesFrame360Entity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK17ImagesFrameEntity")
@interface ImagesFrameEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK14MaterialEntity")
@interface MaterialEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK24ModelMeasuringUnitEntity")
@interface ModelMeasuringUnitEntity : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK15NodeToTagEntity")
@interface NodeToTagEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface PFObject (SWIFT_EXTENSION(ConfigWiseSDK))
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class PFACL;

SWIFT_CLASS("_TtC13ConfigWiseSDK10RoleEntity")
@interface RoleEntity : PFRole
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name acl:(PFACL * _Nullable)acl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC13ConfigWiseSDK11SceneEntity")
@interface SceneEntity : CatalogAwareEntity <PFSubclassing>
+ (NSString * _Nonnull)parseClassName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ConfigWiseSDK27ScnMaterialPropertiesEntity")
@interface ScnMaterialPropertiesEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK25ScnMaterialPropertyEntity")
@interface ScnMaterialPropertyEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK18SnappingAreaEntity")
@interface SnappingAreaEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK12SnappingNode")
@interface SnappingNode : SCNNode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ConfigWiseSDK20TagToMaterialsEntity")
@interface TagToMaterialsEntity : EmbeddedEntity
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13ConfigWiseSDK10UserEntity")
@interface UserEntity : PFUser
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
