# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Uncomment this line if you're using Swift
use_frameworks!

workspace 'examples'

target 'ios-example' do
    project 'ios-example/ios-example.xcodeproj'

    pod 'ConfigWiseSDK'
end
