# Uncomment this line to define a global platform for your project
platform :ios, '14.5'

# TODO [smuravev] There is known issue if we run project on real device iOS v13.3.1 and above
#                 and only used 'personal team' (free apple development program) in 'Signing & Capabilities' settings
#                 of your project. This issue not exist if we use paid apple development account or if we run project
#                 on simulator. See more details about this issue in the following links:
#                  - https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid
#                  - https://github.com/Alamofire/Alamofire/issues/3051
#                  - https://github.com/NativeScript/NativeScript/issues/8294
#                  - https://github.com/flutter/flutter/issues/49504
#                 As a temporary workaround, we use `use_modular_headers!` instead of `use_frameworks!`
#                 Also, run `pod update`, then clean project in Xcode (CMD+SHIFT+K), then run project.
#                 After apple fixes this issue, we must continue use `use_frameworks!`, here.
#use_modular_headers!

# Uncomment this line if you're using Swift
use_frameworks!

workspace 'examples'

target 'ios-example' do
    project 'ios-example/ios-example.xcodeproj'

    # TODO [smuravev] Currently ConfigWiseSDK v1.7.0 (distributed as .xcframework) is non linkable
    #                 under Xcode due, known issue, see (workarounds and recommendations there):
    #                 https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1601
    pod 'ConfigWiseSDK', :git => 'https://github.com/configwise/configwise-sdk-ios.git', :tag => '1.7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        # Forces the minimum to be 14.5 as that's our last deployment target, and new xcode build tools
        # give warnings in Xcode 12
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.5
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.5'
        end

        # Let's disable lint validation of double quotes in .h files.
        # In Xcode 12 this setting is enabled by default => so, we get compilation errors
        # in Pods which have not been migrated to Xcode 12 yet.
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end