# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# TODO [smuravev] There is known issue if we run project on real device iOS v13.3.1 and above
#                 and only used 'personal team' (free apple development program) in 'Signing & Capabilities' settings
#                 of your project. This issue not exist if we use paid apple development account or if we run project
#                 on simulator. See more details about this issue in the following links:
#                  - https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid
#                  - https://github.com/Alamofire/Alamofire/issues/3051
#                  - https://github.com/NativeScript/NativeScript/issues/8294
#                  - https://github.com/flutter/flutter/issues/49504
#                 As a temporary workaround, we use `use_modular_headers!` instead of `use_frameworks!`
#                 Also, run `pod update`, then clean project in Xcode (CMD+SHIFT+K), then run project.
#                 After apple fixes this issue, we must continue use `use_frameworks!`, here.
#use_modular_headers!

# Uncomment this line if you're using Swift
use_frameworks!

workspace 'examples'

target 'ios-example' do
    project 'ios-example/ios-example.xcodeproj'

    pod 'ConfigWiseSDK', '1.5.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        # Forces the minimum to be 12.0 as that's our last deployment target, and new xcode build tools
        # give warnings in Xcode 12
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end

        # Let's disable lint validation of double quotes in .h files.
        # In Xcode 12 this setting is enabled by default => so, we get compilation errors
        # in Pods which have not been migrated to Xcode 12 yet.
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'

        # Here, we exclude 'arm64' architecture if we make build for Simulator.
        # It's required because known issues in Xcode 12 (if we try to publish ConfigWiseSDK).
        # See details here:
        #   - https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end